import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { SidebarProvider } from "@/contexts/SidebarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "admin dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212] text-white`}
      >
        <SidebarProvider>
          {/* Full Page Layout */}
          <div className="flex h-screen overflow-hidden">
            {/* Sidebar (Always Visible) */}
            <Sidebar />

            {/* Main Content */}
            <div className="flex flex-col flex-1 overflow-auto">
              <Header /> {/* Fixed header */}
              <div className="w-full pt-20">
                <main className="max-w-7xl mx-auto px-4 lg:px-8">{children}</main>
              </div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
